site_name: Electricidad básica
nav:
  - Inicio: index.md
  - Introducción a la electricidad: 1_introduccion.md
  - El átomo: 
    - Estructura del átomo: 2_atomo.md
    - Experimenta: 2_1_experimenta.md
  - La corriente eléctrica: 3_corriente.md
  - El circuito eléctrico:
    - Definición y características: 4_circuito_elec.md
    - Componentes eléctricos: 4_1_componentes_elec.md
  - Símbolos y esquemas eléctricos: 5_simbolos.md
  - Magnitudes fundamentales eléctricas: 6_magnitudes.md
  - La Ley de Ohm: 7_ley_ohm.md 


site_url: https://citius70.github.io/electricidad-tecnologia-1eso/
repo_url: https://github.com/citius70/electricidad-tecnologia-1eso.git
repo_name: citius70/electricidad-tecnologia-1eso



theme:
  features:
    - header.autohide
  icon:
    repo: fontawesome/brands/git
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
    background: white
    foreground: black
    code: dark
  palette:
    
   # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
        
   # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a preferencias de sistema



  features:
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch



markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - abbr
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  version:
    provider: mike
